apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rhdhpai802-3
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon/rhdhpai802-3:94a7e2f5e954451a7248a677301ccc4311fba0ce@sha256:bc993e2820913f3fb4a0d53e82f416e0bd24cd2f9d73051b00dabf04a0387028 # use pre-built to bootstrap
          name: app-inference
